name: opentvc tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install AVR dependencies
      run: cd board && sh install.sh
    - name: Build opentvc firmware
      run: cd board && make 
